repos:
  # C/C++ formatter
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.5
    hooks:
      - id: clang-format
        args: [--style=file]
        files: \.(cpp|cc|cxx|c|hpp|h)$
  # Python formatter
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black