# pyproject.toml

[tool.black]
line-length = 80
preview = true
enable-unstable-feature = [
    "string_processing"
]

[tool.docformatter]
wrap-summaries = 80
wrap-descriptions = 80
make-summary-multi-line = true
force-wrap = true