# This example configuration outlines how to configure the srsRAN Project gNB to create a single TDD cell
# transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing. A USRP x310 is configured
# as the RF frontend using split 8. Note in this example an external clock source is not used, so the sync
# is not defined and the default is used.

cu_cp:
  amf:
    # addr: 192.168.2.3
    # bind_addr: 192.168.2.2
    addr: 127.0.0.5
    bind_addr: 127.0.0.1
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: uhd
  device_args: type=x300, addr=192.168.40.2
  srate: 92.16
  clock: gpsdo
  tx_gain: 20
  rx_gain: 30

cell_cfg:
  dl_arfcn: 632628
  band: 78
  channel_bandwidth_MHz: 80
  common_scs: 30
  plmn: 00101
  tac: 7
  pci: 1
  sched_expert_cfg:
    policy_sched_cfg:
      pf_sched:
        pf_sched_fairness_coeff: 1.0
        low_latency_policy: arma
  # tdd_ul_dl_cfg:
  #   dl_ul_tx_period: 5    
  #   nof_dl_slots: 3
  #   nof_dl_symbols: 6
  #   nof_ul_slots: 1
  #   nof_ul_symbols: 4 

log:
  filename: /tmp/gnb.log
  all_level: error

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap