# This example configuration outlines how to configure the srsRAN Project CU/DU to use an O-RU and split 7.2. This is specifically for use
# with the Benetel R550 RU. This config will create a single TDD MIMO cell transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing.
# The parameters used to configure the RU are found in the `ru_ofh` sub-section. This configuration makes used of the OFH Lib from SRS to enable split 7.2.

cu_cp:
  amf:
    addr: 127.0.0.5
    port: 38412
    bind_addr: 127.0.0.1
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_ofh:
  t1a_max_cp_dl: 500
  t1a_min_cp_dl: 258
  t1a_max_cp_ul: 465
  t1a_min_cp_ul: 285
  t1a_max_up: 250
  t1a_min_up: 50
  ta4_max: 200                                                    # Maximum Ta4 on User-Plane in microseconds.
  ta4_min: 0
  is_prach_cp_enabled: true
  is_dl_broadcast_enabled: true
  compr_method_ul: bfp
  compr_bitwidth_ul: 9
  compr_method_dl: bfp
  compr_bitwidth_dl: 9
  compr_method_prach: bfp
  compr_bitwidth_prach: 9
  enable_ul_static_compr_hdr: false
  enable_dl_static_compr_hdr: false
  iq_scaling: 4.5
  cells:
    - network_interface: eno8403np1          # Replace with the DU network interface name (or BDF) for the DU <-> RU connection.
      ru_mac_addr: 8c:1f:64:d1:13:d3           # Replace with the RU MAC address.
      du_mac_addr: c8:4b:d6:9d:5b:1f           # Replace with the MAC address of the DU interface.
      vlan_tag_cp: 5
      vlan_tag_up: 5
      prach_port_id: [4]
      dl_port_id: [0, 1]
      ul_port_id: [0]

cell_cfg:
  dl_arfcn: 637212
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00101"
  tac: 7
  pci: 1
  prach:
    prach_config_index: 7
    prach_root_sequence_index: 1
    zero_correlation_zone: 0
    prach_frequency_start: 0

log:
  filename: /tmp/gnb.log
  all_level: warning

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap
