# This example configuration outlines how to configure the srsRAN Project gNB to create a single TDD cell
# transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing. A USRP x310 is configured
# as the RF frontend using split 8. Note in this example an external clock source is not used, so the sync
# is not defined and the default is used.

cu_cp:
  amf:
    # addr: 192.168.2.3
    # bind_addr: 192.168.2.2
    addr: 127.0.0.5
    bind_addr: 127.0.0.1
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: uhd
  device_args: type=x300, addr=192.168.40.2
  clock: gpsdo
  srate: 92.16
  tx_gain: 30
  rx_gain: 33

cell_cfg:
  dl_arfcn: 641280
  band: 78
  channel_bandwidth_MHz: 80
  common_scs: 30
  plmn: 00101
  tac: 7
  pci: 1
  sched_expert_cfg:
    policy_sched_cfg:
      pf_sched:
        pf_sched_fairness_coeff: 2.0
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 5
    nof_dl_slots: 3
    nof_dl_symbols: 6
    nof_ul_slots: 1
    nof_ul_symbols: 4

expert_execution:
  threads:
    upper_phy:
      pdsch_processor_type: concurrent
      nof_pusch_decoder_threads: 4
      nof_ul_threads: 4
      nof_dl_threads: 8

log:
  filename: /tmp/gnb.log
  all_level: error                    # Optional TEXT (error). Sets a common log level across PHY, MAC, RLC, PDCP, RRC, SDAP, NGAP and GTPU layers.
  lib_level: error                    # Optional TEXT (error). Sets the generic log level.
  e2ap_level: error                   # Optional TEXT (error). Sets the E2AP log level.
  rrc_level: error                    # Optional TEXT (error). Sets the RRC log level.
  ngap_level: error                   # Optional TEXT (error). Sets NGAP log level.
  sec_level: error                    # Optional TEXT (error). Sets the security functions level.
  pdcp_level: error                   # Optional TEXT (error). Sets the PDCP log level.
  sdap_level: error                   # Optional TEXT (error). Sets the SDAP log level.
  cu_level: error                     # Optional TEXT (error). Sets the CU log level.
  mac_level: error                    # Optional TEXT (error). Sets the MAC log level.
  rlc_level: error                    # Optional TEXT (error). Sets the RLC log level.
  f1ap_level: error                   # Optional TEXT (error). Sets the F1AP log level.
  f1u_level: error                    # Optional TEXT (error). Sets the F1u log level.
  gtpu_level: error                   # Optional TEXT (error). Sets the GTPU log level.
  du_level: error                     # Optional TEXT (error). Sets the DU log level.
  fapi_level: error                   # Optional TEXT (error). Sets FAPI log level.
  hal_level: error                    # Optional TEXT (error). Sets the HAL log level.
  phy_level: error                    # Optional TEXT (error). Sets PHY log level.

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap