# Low latency configuration section.

# This is a supplementary configuration file to achieve the low latency. This config will overwrite the `cell_cfg` and
# `expert_phy` options in the base configuration to achieve low latency. This config can be run with the following
# command when running the gNB:
#   sudo ./gnb -c gnb_rf_b200_tdd_n78_20mhz.yml -c low_latency.yml

cell_cfg:
  nof_antennas_ul: 2
  nof_antennas_dl: 2
  pusch:
    min_k2: 4
  pucch:
    sr_period_ms: 5
    min_k1: 4
  mac_cell_group:
    bsr_cfg:
      periodic_bsr_timer: 5
      retx_bsr_timer: 10
  # srs:
  #   srs_period_ms: 2.5